spring.application.name=userservice

spring.datasource.username=${dbusername}
spring.datasource.password=${dbpassword}
spring.datasource.url=jdbc:mysql://localhost:3306/fitness_user_db
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


userservice.email.exists=email id given by the user already exists
userservice.user.notfound=user with the given id not found

spring.client.serviceUrl.defaultZone=http://localhost:8761/eureka/